### ISSUE TITLE
Support new API error types

### ISSUE THREAD

**Issue by TheCorp** [infosimples/two_captcha#4]
There are new API level error types, could you support these in the gem?

https://2captcha.com/api-2captcha#limits

**Comment by barbolo** [comment]
@TheCorp 

We have added the new API errors. Please, check this commit:
https://github.com/infosimples/two_captcha/commit/10d0234b7ae52e3e997fcc80c39dc0a6dd54d41a

We have not added any support for Request Limits. I'm not sure if those errors are reported by the API. Do you have any example of an API response for those cases?

I'm closing this issue for now.

**Comment by TheCorp** [comment]
Thanks!

**Comment by TheCorp** [comment]
@barbolo here is the documentation on the new request limit API responses - https://2captcha.com/api-2captcha#limits

**Comment by TheCorp** [comment]
@barbolo - were you able to look at the new limits (specifically error 1005) and see if the gem can handle those?
