### ISSUE TITLE
conflicts with deathbycaptcha gem during installation

### ISSUE THREAD

**Issue by drinkingcoffee** [infosimples/two_captcha#5]
Hi -- 

I think this is probably harmless, but I receive the following warning/errors during installation, if I also have the deathbycaptcha gem installed:

$ gem install two_captcha
two_captcha's executable "console" conflicts with deathbycaptcha
Overwrite the executable? [yN]  y
two_captcha's executable "setup" conflicts with deathbycaptcha
Overwrite the executable? [yN]  y

**Comment by barbolo** [comment]
Thanks for reporting this issue @drinkingcoffee. It should be harmless, but really annoying.
