### ISSUE TITLE
ReCaptcha Solver v3 

### ISSUE THREAD

**Issue by stuartweir** [infosimples/two_captcha#6]
As per https://2captcha.com/solving_recaptcha_v3, 2Captcha has announced that they have a beta for solving ReCaptcha v3's.

From the looks of it, it's entirely based on the user "score", not based on actually solving a Captcha, but it seems to have a very similar API as the v2. I'm creating this Issue as a suggestion to integrate v3 into this codebase, however I am willing to put in at least some of the work to have this integration.

Please let me know thoughts, etc. 

I am a newer Software Developer, so I may need a bit of guidance, but I'd love to contribute anyway. 

-Stu

**Comment by indritgjergji** [comment]
view-source:https://freebitco.in/cdn-cgi/apps/head/gUhj1EGh0R2kyI9wfTVciuyeAFY.js

**Comment by stuartweir** [comment]
@rafaelivan do you have any input?
